- name: Copy
  hosts: docker_server
  become: no
 
  tasks:
  - name: task copy
    copy:
     src: index.html 
     dest: t123
     
  - name: Just get the list from default pip
    community.general.pip_package_info:
 
