- name: Copy
  hosts: docker_server
  become: yes


  tasks:
  - name: copy war
    copy:
     src: target/
     dest: CI-CD/target/
 
  - name: copy docker
    copy:
     src: docker/
     dest: CI-CD/
     
  - name: copy mysql-dump
    copy:
     src: mysql-dump/
     dest: CI-CD/mysql-dump/
  
      
  - name: pip install
    apt:
     pkg: python3-pip
     state: present


  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl',
 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
  - name: Add Docker GPG apt Key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: Add Docker Repository
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu bionic stable
     state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
     name: docker
     
  - name: Installing docker compose
    pip:
     name: docker-compose
     state: present
     
  - name: dicker-compouse up
    shell:
     cmd: "docker-compose up -d"
     chdir: CI-CD/
     
  - name: docker restart
    shell:
     cmd: "docker-compose up -d --no-deps --build"
