- name: Copy
  hosts: docker_server
  become: no
 
  tasks:
  - name: task copy
    copy:
     src: index.html 
     dest: t123
     
  - name: pip install
    apt:
     pkg: python3-pip
     state: present
     
  - name: docker install
    pip:
     name: docker
     state: present
